// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUYvZ_TAF7IN-ArpF1H-9K_sYaFfu7AI',
    appId: '1:572951591986:web:0e138609d6d0f1ebae102b',
    messagingSenderId: '572951591986',
    projectId: 'mobile-agi',
    authDomain: 'mobile-agi.firebaseapp.com',
    storageBucket: 'mobile-agi.appspot.com',
    measurementId: 'G-2LB19K1T7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0mEaH9mglZp_lVo59hmv-LXA5oGdBUHw',
    appId: '1:572951591986:android:c4c59bcded2ac827ae102b',
    messagingSenderId: '572951591986',
    projectId: 'mobile-agi',
    storageBucket: 'mobile-agi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqo-BtMWZ3LKpbVpkDhT2S2eAH6QcjP1I',
    appId: '1:572951591986:ios:be65186e13c2201aae102b',
    messagingSenderId: '572951591986',
    projectId: 'mobile-agi',
    storageBucket: 'mobile-agi.appspot.com',
    androidClientId: '572951591986-v0qs38k76adgi0bua9vr76b79puh72b1.apps.googleusercontent.com',
    iosClientId: '572951591986-95vujte0ep585j83161etub186vopefj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileagi.mobileAgi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqo-BtMWZ3LKpbVpkDhT2S2eAH6QcjP1I',
    appId: '1:572951591986:ios:95fefdc07a88fe7dae102b',
    messagingSenderId: '572951591986',
    projectId: 'mobile-agi',
    storageBucket: 'mobile-agi.appspot.com',
    androidClientId: '572951591986-v0qs38k76adgi0bua9vr76b79puh72b1.apps.googleusercontent.com',
    iosClientId: '572951591986-ldefd42chb3kkm62iajmea3bimrc7gof.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileagi.mobileAgi.RunnerTests',
  );
}
